version: 2
jobs:
  test:
    docker:
    - image: circleci/ruby:2.6.3
    steps:
    - checkout
    - run:
        name: Bundler installation
        command: gem install bundler
    - run:
        name: Dependencies installation
        command: bundle check || bundle install
    - run:
        name: Rubocop check
        command: bundle exec rubocop
    - run:
        name: Fasterer check
        command: bundle exec fasterer
    - run:
        name: RSpec check
        command: bundle exec rspec